AWSTemplateFormatVersion: '2010-09-09'
Description: Nella, Miika & Razan TJ Template

#tj - Tuntijärjestelmä lyhenne nimeämiseen

Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    Description: Enter t2.micro, Default is t2.micro.
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

# Template Resurssit
Resources:

  tuntijbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tuntijbucket

# aws cloudformation create-stack --stack-name tj-stack --template-body file://cf-template.yaml

  tuntijSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: tuntij-queue-1
      MessageRetentionPeriod: 300 # 5 minuttia

# aws cloudformation deploy --template-file cf-template.yaml --stack-name tj-stack

  tuntijInstance1:
    Type: 'AWS::EC2::Instance'
    Properties:
     
      AvailabilityZone: us-east-1a
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceTypeParameter


    
     

